"""Recipe catalog matched against virtual freezer species names."""

RECIPE_CATALOG = [
    {
        "id": "garlic-butter-prawns",
        "keywords": ["prawn", "shrimp", "udang"],
        "title": "Garlic Butter Prawns",
        "minutes": 20,
        "difficulty": "Easy",
        "image_tag": "prawn",
        "ingredients": [
            "Prawns (peeled)",
            "Butter",
            "Garlic (minced)",
            "Lemon juice",
            "Fresh parsley",
            "Salt & black pepper",
        ],
        "steps": [
            "Pat prawns dry and season with salt and pepper.",
            "Sauté minced garlic in butter until fragrant.",
            "Add prawns and cook 2–3 minutes per side until pink.",
            "Finish with lemon juice and chopped parsley. Serve immediately.",
        ],
    },
    {
        "id": "sambal-prawns",
        "keywords": ["prawn", "shrimp", "udang"],
        "title": "Malaysian Sambal Prawns",
        "minutes": 25,
        "difficulty": "Medium",
        "image_tag": "prawn",
        "ingredients": [
            "Prawns",
            "Shallots",
            "Garlic",
            "Dried chillies",
            "Cooking oil",
            "Tamarind paste",
            "Sugar & salt",
        ],
        "steps": [
            "Blend shallots, garlic, and dried chillies into a paste.",
            "Fry the paste in oil until the oil splits and smells aromatic.",
            "Add prawns and stir-fry until almost cooked.",
            "Season with tamarind, sugar, and salt. Serve with hot rice.",
        ],
    },
    {
        "id": "steamed-fish-ginger",
        "keywords": ["fish", "snapper", "tilapia", "ikan", "salmon", "mackerel"],
        "title": "Steamed Fish with Ginger & Soy",
        "minutes": 22,
        "difficulty": "Easy",
        "image_tag": "fish",
        "ingredients": [
            "Whole fish or fillets",
            "Fresh ginger (julienned)",
            "Light soy sauce",
            "Sesame oil",
            "Spring onions",
        ],
        "steps": [
            "Score the fish and place ginger strips on top.",
            "Steam over high heat for 10–12 minutes until flaky.",
            "Heat soy sauce, sesame oil, and spring onion in a small pan.",
            "Pour the hot sauce over the fish and serve.",
        ],
    },
    {
        "id": "fried-fish-tumeric",
        "keywords": ["fish", "ikan", "tilapia", "mackerel"],
        "title": "Turmeric Fried Fish",
        "minutes": 30,
        "difficulty": "Medium",
        "image_tag": "fish",
        "ingredients": [
            "Fish (whole or steaks)",
            "Turmeric powder",
            "Salt",
            "Rice flour (optional)",
            "Oil for frying",
            "Sambal belacan (to serve)",
            "Cucumber slices",
        ],
        "steps": [
            "Marinate fish with turmeric, salt, and a little water for 15 minutes.",
            "Coat lightly with rice flour if desired.",
            "Shallow-fry until golden and crisp on both sides.",
            "Serve with sambal belacan and cucumber slices.",
        ],
    },
    {
        "id": "salted-egg-squid",
        "keywords": ["squid", "sotong", "cuttlefish"],
        "title": "Salted Egg Butter Squid",
        "minutes": 18,
        "difficulty": "Medium",
        "image_tag": "squid",
        "ingredients": [
            "Squid (cleaned, rings)",
            "Cornflour",
            "Butter",
            "Salted egg yolk (mashed)",
            "Curry leaves",
            "Bird's eye chilli",
            "Oil for frying",
        ],
        "steps": [
            "Coat squid rings lightly in cornflour.",
            "Quick-fry squid for 1 minute and set aside.",
            "Melt butter, stir in mashed salted egg yolk until creamy.",
            "Toss squid back in the sauce with curry leaves and chilli.",
        ],
    },
    {
        "id": "grilled-squid",
        "keywords": ["squid", "sotong"],
        "title": "Grilled Squid with Lime",
        "minutes": 15,
        "difficulty": "Easy",
        "image_tag": "squid",
        "ingredients": [
            "Squid (cleaned)",
            "Lime juice",
            "Garlic",
            "Olive oil",
            "Salt & pepper",
            "Lime wedges",
        ],
        "steps": [
            "Marinate cleaned squid with lime, garlic, and olive oil.",
            "Grill on high heat 2–3 minutes per side.",
            "Brush with extra marinade while grilling.",
            "Slice and serve with lime wedges.",
        ],
    },
    {
        "id": "chilli-crab",
        "keywords": ["crab", "ketam"],
        "title": "Sweet & Spicy Chilli Crab",
        "minutes": 35,
        "difficulty": "Hard",
        "image_tag": "crab",
        "ingredients": [
            "Fresh crab",
            "Ginger & garlic",
            "Chilli paste",
            "Tomato sauce",
            "Egg",
            "Chicken stock",
            "Cornstarch slurry",
            "Fresh coriander",
        ],
        "steps": [
            "Clean crab and crack the shell for even cooking.",
            "Stir-fry ginger, garlic, and chilli paste until fragrant.",
            "Add crab, tomato sauce, egg, and stock. Simmer 12–15 minutes.",
            "Thicken with cornstarch slurry and garnish with coriander.",
        ],
    },
    {
        "id": "black-pepper-crab",
        "keywords": ["crab", "ketam"],
        "title": "Black Pepper Crab",
        "minutes": 30,
        "difficulty": "Medium",
        "image_tag": "crab",
        "ingredients": [
            "Crab pieces",
            "Cornflour",
            "Butter",
            "Garlic",
            "Crushed black pepper",
            "Oyster sauce",
            "Water",
        ],
        "steps": [
            "Coat crab pieces lightly in cornflour and shallow-fry until red.",
            "Sauté butter, garlic, and crushed black pepper.",
            "Return crab to the wok with oyster sauce and a splash of water.",
            "Toss until the sauce coats the shell and serve hot.",
        ],
    },
    {
        "id": "clam-soup",
        "keywords": ["clam", "mussel", "shellfish", "lala"],
        "title": "Clear Clam Soup with Ginger",
        "minutes": 20,
        "difficulty": "Easy",
        "image_tag": "shellfish",
        "ingredients": [
            "Fresh clams",
            "Ginger slices",
            "White pepper",
            "Water or light stock",
            "Salt",
            "Coriander",
        ],
        "steps": [
            "Soak clams in salted water to remove sand.",
            "Boil water with ginger and white pepper.",
            "Add clams and cook until shells open (discard any that stay closed).",
            "Season lightly and finish with coriander.",
        ],
    },
    {
        "id": "seafood-fried-rice",
        "keywords": ["prawn", "fish", "squid", "crab", "seafood"],
        "title": "Mixed Seafood Fried Rice",
        "minutes": 25,
        "difficulty": "Easy",
        "image_tag": "fish",
        "ingredients": [
            "Cooked rice (day-old)",
            "Mixed seafood (prawn, fish, squid)",
            "Garlic",
            "Eggs",
            "Light soy sauce",
            "White pepper",
            "Spring onions",
            "Cooking oil",
        ],
        "steps": [
            "Use day-old rice for the best texture.",
            "Stir-fry seafood quickly and set aside.",
            "Fry garlic, eggs, and rice with soy sauce and white pepper.",
            "Fold seafood back in with spring onions before serving.",
        ],
    },
]
